[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/lalamove-quote"
  to = "/.netlify/functions/lalamove-quote"
  status = 200
  force = true
