[build]
  command = ""
  publish  = "."

[functions]
  node_bundler = "esbuild"
  directory    = "netlify/functions"

[[redirects]]
  from = "/api/lalamove-quote"
  to   = "/.netlify/functions/lalamove-quote"
  status = 200

[build.environment]
SECRETS_SCAN_ENABLED = "false"
